env:
  global:
  - secure: XZg2EpuYSH4VkO1ari1+jm1TzP7Mt6AUhf+1tE2off+f+1Fdgkzo7EBwaLmYdpi5pqRjL8ywLJSSUX3T8KtuOpOHc9AiasnEzOtqNEsOgmiu8HpAGbtYtUHUJ6PwOHWlazcuWD/QxoA5Y5L0ykpBrcmomaXAVI1OULq6zAokyvnGhyTwbByCGsxWCl8jQu4NQ6X82WAvPwnjoSaJ0B50Sx7x2YgV3KcdFqraxvf905vokeT5TtlyFG0TRm3xYz9ZZgx+UiqJiK20lovhF1k7YuXj0hieBopN/hXI0wFFwFSqhJpqgWcCw0qwreVJJ5E5VF0qrC/9Ml8myVHbmXKdjidDcJqBMUN26vQSMjTgm5qpkd0dFGiQNbol1GN81RpqBiuzqNnBjHIkbY4FmuIEaHFTWdN3KUywvla318tovnVUKOO4+7ebv7gw3yaiDxicRCdG7ufgSYHW3xVCzYXNlcOR3T27nfj9Rmwsoy7u3qA1764D7xmeDjI+Hoj5pwpy6gtQGqGdV9D+IVJnex6LrY+6a0FJL88FBbYxtYwnuHFUtV6RGAFQS1b2uWYt0A/ofyuP+Pkc0H2/NbXCJ5Vi5vF4hwoZuk6hzuhULIVsgwVR7gxWUjorWsDbCdlQVdtSd6uFKyL+xo/krw0QhSgl0fwjG8muDNfn2W+uaO3S2qU=
  - secure: V/MNomAZEdtR97uMehh8vbWWize1bR2RCv+RkF2H5tRw/5XkhHHZmen6yV6xVK3R2ReSk6QCAgW18zj3K3IYo5B0x2gK0VbzyKV7iin30GeCWVrbWCbyDYFiPypvj6mfpbIIg2nabFPieJ+UcWIfyg5fC0f5G0ec2dENw1Vy6WHEUnZ581tFCUkL91j8LAW38Vv0LQn/XbJDZnDx0JVPmd4kBjDZfYTeG4fFZq5vBFgqdUqRGiPWqHT3kspbTp+dPfY5IpPM60+dTydtpdB9CuogWjHsfNS9unVLxkPREXo49bZB4ewSZoSKBqO2TP3T/WZGcXkOiCUutv7LLhwKXsSfW+RNlznMXsWgTOss5rHM1RFqr628A7Rp+ACaItaU1J/6Up1yUhZU9XgANqdk1YdfOrzLWITv+smkjD3ECTk++5S3dIldq2mVgyfnXPf/xfCyQqpOMfWs0MwxNCrDnG9UkIaWFKhuvOgqfG3qzfyUvDv4st4wdKy0w75wGlNxLLSAMB41BLhVUcN31XVKWSN+APRTIyJSn1VX/Y21r4UVSm65wGZ6L1fP5bZM03uehoaRWFWh1Qko9jJRiFSO8PQ7zomJaAeh2o5962dlHfYi6vBqljZqZ+iqXinyLDdi8/EKePmUpNkYFdIhBLB6JWgPrYnem9SlYC9hoP/Nk5k=
notifications:
  email:
    recipients:
    - adrian.herrera@intuitivetech.com
    - megan.wood@intuitivetech.com
    - andrew.johnson@intuitivetech.com
    on_success: never
    on_failure: always
  slack:
    secure: cdO3E9c06xOpESuJyRtAJRzwNIlQLGs1cbcX8W0Uhvx6+5ssYSe5xI/OWV5L1CU+Yyi26i2GndmYoF9dRJvEhozWBFlXZOcZJe4ge7gOliIw2U70DZ/spm5wtnrqjQDIHyrY0TyTE4403uKiFIGkD2leMUREelBEJhyySwL6ts9yxA4JIcGWBcBc3c0LlTHJESNr2i1qzM1YpRgcfEEB3IbRahUAA0xVStxojIm9eewhrfyDIMY13/bDJb4w1pZmBAtMM22u+1+3yhUlOMj8lRVXndma6XfugTN0P32viWrCYn/K75BGjkllKtkPHEytu7JY14dOMcvpoFV4/N79KCFcr3h4NItWVim5540VFBH1sPDpY/5K268y9z/W1Zn+3+VsVVB7FZH3k67XTcmThx3Hl0xC0u4wiWDWCbds2K54Y3U5lQ1LttPoPSrLJQ2zw4Ce2wxwLloY786MPQUWmyK8ocpC1NExVYsqEBaJkO+SDwDAsk03QnTewWHZ2ciN5bE6sITbbeym00Qx+C02NnseNJNneVWtgNequNiYRu2CTnUX6anmz+FLcMKRt+WQr+Rw22K0c3sx+utUCGPCYQJeyRgHfyQj9EFGynso+ooPsbL540UNbIFYlip1KTyaLd7cvzi+B0yyzRjKLFXFacr5KCvAC+L+9JeRqtBCzgY=
    on_success: change
    on_failure: always
sudo: required
services:
- docker
script:
#- docker login -u $DOCKER_USER -p $DOCKER_PASS
- make all
