env:
  global:
  - secure: LdoVVJA/Z69lY9NxV63ZN3fjCzNZz5S4QL4b6oCLJvx7Xc92HDniZ4T0qaDDMkZjm7UrPvOsaEjClSjc9IrwFscj9SDXg3EvrVmerpyLDK0GkjXN3axcryxVoWjVGLeyHf4q0MFItjdWzyE6Ps9V0rXXUZ+5l1OP7iJDPNu06kLY+bqYRPAaweUTGyqlOKJOAElP+ZG8GZJ/7VLU/mjIVcbMcl1NA2AEpeNpEERVT8sVR6sY/3rhgn3cmMGvlP/7rsCDdntNgC7m+JJIzm6rZy9S2ZZtO5O3ckCdFUv5Al3QzPgtz+sbblfnYNfXoEIQ2+JWhKOZB8KELTH12CjUoPOdvsHT4L+PE3eZDydhy2AdWZYU/qFzNCC2wW5buAyftiu2NiwzxGZMbvflSPCcBD8YyqDyO6CLE6hUXFkxLxfXqainFes/7UzqOFRkOf/5AoBZTwweIPodqmY3Ge+0J+yG5IqReUJ4MJZ+OtcSjPj9WmOY4GCAS3FXbGYsQ1Q3b2ZRjXzLiFTprf6M5XG5J7N4qZoOJbZNCFoKmI7883awQNgGPljqtWIlZmxrcCzlwxB8Wc5RLZdZ1R5jm/7Zj0BIu7Oq3IQ0OJz160BhZ5zH7KgiDFS3Pt7nGlWx9YzC04/GFliQbXCYmRTTwiqSX/gHpBjj78ZlDzDgZ3rj3hE=
  - secure: XCVVWudZkktA14oPiT6she2mZPSLKbI5YvtKMsz3sxXyWfQevYxKTsYTKYH1mR5PSwP3XLe+R4ryz+x2RD0X7u0GZMDRFSAQ+OrOGGn19OHH5WG936oF82M9WXP6ajbEnh0xwPJuH1+sws+S2ZjyDm0ZaXQnMBH4aVHlBDdtLwI/wXbYQ4NKaFmDQqseI+HhcgVnww+vcvhh7dLa6LeYJNEG3lNVptPH1de2UYKDC6duvP7yBdedC/NN4ihNFO1K8mDJuhSzg6WZOL9u1Dz1rsVFo1+9TsRyqS0SJMjNXLx91hsnJLV4BGDun4HYuCllsauynuKbQu93ih8SAaMSwSwqu1dAgfNySlLZHpyBZIoyEnxduH6UddzC/F/O93I4rAh5hsYIoTEL7mSZDW2ya+fywrow/vaHNgnpS6YSXjN20O1CpgClaXQzdP4z+WDzBQn50cOflbY1Hs9W5dTbsphOk14ysoyd339tT0c0UMHNhPps0c23YQ5Tw8Kv7nbe3xidLXqHs+Z6V+NMlxkYlp+VZojba6YInVLmIMYHOQKkOmH6/yJ433D/qUQeoJ6Jd1ySwkj92NX8a+99ldmkKHg4u891WsIOkWzcpSvm9AgG3mMO6tI4smvNDlb0o3OIu9Ztzh0gEgTrEtIGEyRGwlUM43gjOMvzSBXU68m9LqE=
  - secure: UG8Q5dqyN+9F8VZWsZuCc51KXsnZnbQX5dVbrD2digQ6RjLjwtn9KSQ2P7rUVtM3gZ9r3TS/6BETKGm22T3HpeafAIp54teZ71Mk6G1ZUUHUuvcfRbLwpR4p7YaIX4RkHojv8zxUVDrZMQscw7JYRC/IQin3itfN/z7Yu+MQFakEbGlhUeImtPOmjGlnu4N6Yz7s5ugm10wC0zwtsc7OqisMdIrnBMw92vlifgpVAdQfNd2arMemeoRtLWsh0jSErojhLF3zStlUU21aWGgNhZHZXxgsh631rrl9LrXKnCdMtdei39qmXzVoO5oc/z3h4B4FVRM6/ZSirm0bbImMdER00Kxm8NerI0MtabSYcNI3mRFTPzJKHjWwV2Q01w0K/uPZ3oG0+SbZhzPBnE8zT72elgxsLgRHQWuTNf5IFRKA5m9IEIw6waKeCC8Lfef3hB3/bwRBAuJppMJ3cirKB/CnB87rZq+/htm9gA0QjhPBp5Uda7w9EE2/FWbe4IonPY97Psl2EfC/M2ncSBnSmgmBkCdbCfSxtWSKNhnceX4z6JOFCL2LFUHLcvN7bR8guflMzgFgstgXY12bdXmlvlKFaiIvcxqQgaMlC3pE0O0bKs/7f/+BxOvYJBa8EVyTRrC1OUxJLmXiyRy/HBtOsztysu+mnc0ycH/kK9Ta770=
  - COMMIT=${TRAVIS_COMMIT::8}

notifications:
  email:
    recipients:
    - adrian.herrera@intuitivetech.com
    - megan.wood@intuitivetech.com
    - andrew.johnson@intuitivetech.com
    on_success: never
    on_failure: always
  slack:
    secure: cdO3E9c06xOpESuJyRtAJRzwNIlQLGs1cbcX8W0Uhvx6+5ssYSe5xI/OWV5L1CU+Yyi26i2GndmYoF9dRJvEhozWBFlXZOcZJe4ge7gOliIw2U70DZ/spm5wtnrqjQDIHyrY0TyTE4403uKiFIGkD2leMUREelBEJhyySwL6ts9yxA4JIcGWBcBc3c0LlTHJESNr2i1qzM1YpRgcfEEB3IbRahUAA0xVStxojIm9eewhrfyDIMY13/bDJb4w1pZmBAtMM22u+1+3yhUlOMj8lRVXndma6XfugTN0P32viWrCYn/K75BGjkllKtkPHEytu7JY14dOMcvpoFV4/N79KCFcr3h4NItWVim5540VFBH1sPDpY/5K268y9z/W1Zn+3+VsVVB7FZH3k67XTcmThx3Hl0xC0u4wiWDWCbds2K54Y3U5lQ1LttPoPSrLJQ2zw4Ce2wxwLloY786MPQUWmyK8ocpC1NExVYsqEBaJkO+SDwDAsk03QnTewWHZ2ciN5bE6sITbbeym00Qx+C02NnseNJNneVWtgNequNiYRu2CTnUX6anmz+FLcMKRt+WQr+Rw22K0c3sx+utUCGPCYQJeyRgHfyQj9EFGynso+ooPsbL540UNbIFYlip1KTyaLd7cvzi+B0yyzRjKLFXFacr5KCvAC+L+9JeRqtBCzgY=
    on_success: change
    on_failure: always
sudo: required
language: PYTHON
services:
- docker
script:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- make all
